// playwright-cli run-code --filename web_mvp/diagnostics/check_schedule_batch_ui.js
// All API responses and side effects below are synthetic. Never calls WeChat or Hook.
async (page) => {
 const checks=[],errors=[],requests=[],gates=[];
 const check=(value,name)=>{if(!value)throw Error(name);checks.push(name);},clone=value=>JSON.parse(JSON.stringify(value));
 const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);const gate={promise,resolve};gates.push(gate);return gate;};
 const groups=[{id:'batch-same@chatroom',name:'同名会话',conversationKind:'group'},{id:'batch-same@im.chatroom',name:'同名会话',conversationKind:'group'},{id:'batch-direct',name:'合成私聊',conversationKind:'direct'},{id:'batch-unwatched',name:'未读取会话',conversationKind:'group'}];
 const source={id:'batch-account-a',revision:'r1',status:'snapshot_ready',createdAt:'2026-10-04T01:00:00Z',updatePolicy:'on_change'};
 const state={account:source.id,selfId:'synthetic-self',name:'合成批量账号',csrfToken:'synthetic',connection:{status:'snapshot_ready'},groups,selected:groups[0].id,watchedGroups:groups.slice(0,3).map(row=>row.id),jobs:[],outbox:[],runtime:{mode:'database',connected:true,platform:'Windows',source,capabilities:{read:true,canSend:false,hookSendInterface:false,groupSend:false,automaticReplies:true,scheduledSend:true,scheduleTemplates:true,scheduleWindows:true,scheduleBatches:true,mentions:true,media:false}}};
 const rule={enabled:false,text:'保留的回复草稿',cooldown:30,mode:'reply'};
 const template={id:'synthetic-batch-template-0001',name:'合成索价',text:'{{客户}}，请提供今日价格。',version:1,variables:['客户']};
 const profiles=new Map([[groups[0].id,{values:{},overrideText:null}],[groups[1].id,{values:{},overrideText:'本群完整覆盖：{{保留为文字}}\n请提供已批准范围内的资料。'}],[groups[2].id,{values:{客户:'私聊客户 😀 <literal>'},overrideText:null}]]);
 const jobSets=new Map(),receipts=new Map();let serial=0,templatesAvailable=true,capacityCount=null,forceDuplicate=false,forceStale=false,loseResponse=false,writeGate=null,previewGate=null;
 const jobsFor=account=>{if(!jobSets.has(account))jobSets.set(account,[]);return jobSets.get(account);};
 const due=Date.parse('2026-10-09T23:59:00+08:00')/1000;
 const makeJob=(id,body,record)=>({id,group_id:record.groupId,targetName:record.targetName,text:record.text,enabled:true,state:'active',issue:'',mode:body.mode,clock:body.clock,at:body.at,weekdays:body.mode==='weekly'?body.weekdays:body.mode==='daily'?[1,2,3,4,5,6,7]:[],windowMinutes:body.windowMinutes,nextRun:due,runs:[],last_result:''});
 jobsFor(source.id).push(makeJob('existing-job',{mode:'daily',clock:'07:00',at:'',windowMinutes:2},{groupId:groups[0].id,targetName:groups[0].name,text:'已有独立计划'}));
 const templateDetail=groupId=>({...template,targets:[...profiles.keys()].map(id=>({groupId:id,targetName:groups.find(row=>row.id===id).name})),groupId,profile:clone(profiles.get(groupId)||{values:{},overrideText:null})});
 const previewFor=body=>{
  const jobs=jobsFor(body.account),records=body.groupIds.map(groupId=>{const target=groups.find(row=>row.id===groupId),profile=profiles.get(groupId)||{values:{},overrideText:null},missing=profile.overrideText===null?template.variables.filter(key=>!profile.values[key]?.trim()):[];
   const text=profile.overrideText===null?(missing.length?'':template.text.replace(/\{\{([^{}]+)\}\}/g,(_,key)=>profile.values[key])):profile.overrideText;
   const duplicate=forceDuplicate&&groupId===groups[0].id||jobs.some(row=>['active','paused'].includes(row.state)&&row.group_id===groupId&&row.text===text&&row.mode===body.mode&&row.clock===body.clock&&row.at===body.at&&row.windowMinutes===body.windowMinutes&&(body.mode!=='weekly'||JSON.stringify(row.weekdays)===JSON.stringify(body.weekdays)));return {groupId,targetName:target.name,text,contentSource:profile.overrideText===null?'template':'override',error:duplicate?'已有启用或暂停的相同计划':missing.length?'请填写变量：'+missing.join('、'):!text.trim()?'完整覆盖正文不能为空':'',missing,existingCount:jobs.filter(row=>row.group_id===groupId).length,duplicate};});
  const invalidCount=records.filter(row=>row.error).length,existingCount=capacityCount===null?jobs.length:capacityCount,issues=existingCount+records.length>500?['本批创建后将超过500条本机任务记录上限。']:[];
  const canCreate=!invalidCount&&!issues.length;return {templateId:template.id,templateVersion:template.version,templateName:template.name,mode:body.mode,clock:body.clock,at:body.at,weekdays:body.mode==='weekly'?body.weekdays:[],windowMinutes:body.windowMinutes,nextRun:due,deadline:due+body.windowMinutes*60,records,readyCount:records.length-invalidCount,invalidCount,existingCount,capacity:500,canCreate,previewDigest:canCreate?'synthetic-digest-'+template.version:'',issues};
 };
 const handler=async response=>{
  const request=response.request(),raw=request.url(),path=raw.split('?')[0].replace(/^https?:\/\/[^/]+/,''),query=Object.fromEntries((raw.split('?')[1]||'').split('&').filter(Boolean).map(part=>{const [key,value='']=part.split('=');return [decodeURIComponent(key),decodeURIComponent(value.replace(/\+/g,' '))];})),body=request.method()==='POST'?request.postDataJSON():null;
  requests.push({path,query,body,method:request.method()});
  if(path==='/api/state')return response.fulfill({json:{...state,jobs:jobsFor(state.account)}});
  if(path==='/api/database')return response.fulfill({json:{mode:'database',configured:true,busy:false,config:{sourceRoot:'D:\\Synthetic\\db',autoRefresh:true},source:state.runtime.source}});
  if(path==='/api/select')return response.fulfill({json:{ok:true}});
  if(path==='/api/group'||path==='/api/messages')return response.fulfill({json:{watching:true,members:[],messages:[],outbox:[],reply:rule}});
  if(path==='/api/windows/hook/status')return response.fulfill({json:{available:false,status:'disabled',issue:'合成测试不连接 Hook'}});
  if(path==='/api/schedule-templates')return response.fulfill({json:{templates:templatesAvailable?[{...template,targetCount:profiles.size}]:[]}});
  if(path==='/api/schedule-templates/item')return response.fulfill({json:templateDetail(query.groupId)});
  if(path==='/api/schedule-templates/profile'){
   if(body.version!==template.version)return response.fulfill({status:409,json:{code:'template_conflict',error:'模板版本已变化'}});
   profiles.set(body.groupId,{values:body.values,overrideText:body.overrideText});template.version++;return response.fulfill({json:templateDetail(body.groupId)});
  }
  if(path==='/api/jobs/batch/preview'){
   if(body.templateVersion!==template.version)return response.fulfill({status:409,json:{code:'template_conflict',error:'模板版本已变化'}});
   const data=previewFor(body),held=previewGate;previewGate=null;if(held){held.started.resolve();await held.done.promise;}return response.fulfill({json:data});
  }
  if(path==='/api/jobs/batch'){
   const key=body.account+'|'+body.requestId,old=receipts.get(key);
   if(old){if(old.input!==JSON.stringify(body))return response.fulfill({status:409,json:{code:'batch_conflict',error:'请求标识已绑定其他规格'}});return response.fulfill({json:{batchId:key,createdCount:old.ids.length,jobs:jobsFor(body.account).filter(row=>old.ids.includes(row.id)),reused:true}});}
   if(forceStale){forceStale=false;return response.fulfill({status:409,json:{code:'batch_conflict',error:'首期时间已变化，请重新预览'}});}
   const data=previewFor(body);if(!data.canCreate||body.templateVersion!==template.version)return response.fulfill({status:409,json:{code:'batch_conflict',error:'模板或整批状态已变化'}});
   const held=writeGate;writeGate=null;if(held){held.started.resolve();await held.done.promise;if(held.fail)return response.fulfill({status:409,json:{code:'batch_conflict',error:'旧账号批次失败'}});}
   const jobs=data.records.map(record=>makeJob('batch-job-'+(++serial),body,record));jobsFor(body.account).push(...jobs);receipts.set(key,{input:JSON.stringify(body),ids:jobs.map(row=>row.id)});
   if(loseResponse){loseResponse=false;return response.abort('failed');}
   return response.fulfill({json:{batchId:key,createdCount:jobs.length,jobs,reused:false}});
  }
  return response.fulfill({status:400,json:{error:'Synthetic test blocks this API.'}});
 };
 const onError=error=>errors.push(error.message);page.on('pageerror',onError);await page.route('**/api/**',handler);
 const ready=()=>page.waitForFunction(()=>scheduleBatchRequest===null),refresh=async()=>{await page.waitForFunction(()=>!pollBusy);await page.evaluate(()=>poll());};
 const open=async()=>{await page.locator('#schedule-batch-open').click();await ready();};
 const close=async()=>{await page.locator('#schedule-batch-dialog .dialog-heading .close-dialog').click();await page.waitForFunction(()=>!document.getElementById('schedule-batch-dialog').open);};
 const preview=async()=>{await page.locator('#schedule-batch-preview').click();await ready();};
 const choose=async()=>{await page.locator('#schedule-batch-template').selectOption(template.id);await page.locator('#schedule-batch-select-visible').click();await page.locator('#schedule-batch-mode').selectOption('weekly');for(const day of [2,4])await page.locator('#schedule-batch-weekdays input[value="'+day+'"]').uncheck();await page.locator('#schedule-batch-clock').fill('23:59');await page.locator('#schedule-batch-window').fill('5');};
 const visible=async(selector,name)=>{const locator=typeof selector==='string'?page.locator(selector):selector;await locator.scrollIntoViewIfNeeded();const ok=await locator.evaluate(node=>{const r=node.getBoundingClientRect(),d=node.closest('dialog').getBoundingClientRect(),hit=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return r.width>0&&r.height>0&&r.top>=Math.max(d.top,0)&&r.bottom<=Math.min(d.bottom,innerHeight)+1&&r.left>=0&&r.right<=innerWidth+1&&!!hit&&(hit===node||node.contains(hit));});check(ok,name);};
 try{
  await page.setViewportSize({width:1440,height:1040});await page.reload();await page.waitForFunction(()=>document.getElementById('selected-name').textContent.includes('同名会话'));await page.locator('[data-view="schedules"]').click();await open();
  check((await page.locator('#schedule-batch-groups').innerText()).includes('@im.chatroom')&&(await page.locator('#schedule-batch-groups').innerText()).includes('batch-direct')&&!(await page.locator('#schedule-batch-groups').innerText()).includes('batch-unwatched'),'known_watched_mixed_and_private_targets_are_selectable');await choose();
  await page.locator('#schedule-batch-search').fill('batch-direct');check((await page.locator('#schedule-batch-count').innerText()).includes('已选择 3')&&await page.locator('#schedule-batch-groups input:checked').count()===1,'search_keeps_hidden_selected_targets');await page.locator('#schedule-batch-search').fill('');await preview();
  const first=requests.filter(row=>row.path==='/api/jobs/batch/preview').at(-1).body;check(first.groupIds.length===3&&JSON.stringify(first.weekdays)==='[1,3,5]'&&first.windowMinutes===5&&!Object.hasOwn(first,'text'),'preview_sends_ids_template_version_and_shared_calendar_only');
  check((await page.locator('#schedule-batch-results').innerText()).includes('缺少：客户')&&await page.locator('#schedule-batch-create').isDisabled(),'missing_variable_blocks_whole_batch');
  const incomplete=page.locator('.schedule-batch-record').filter({hasText:groups[0].id});await incomplete.getByRole('button',{name:'配置此会话模板'}).click();await page.waitForFunction(()=>scheduleTemplateRequest===null&&scheduleTemplateDetail!==null);
  check(await page.locator('#schedule-template-select').inputValue()===template.id&&await page.locator('#schedule-template-target').inputValue()===groups[0].id,'missing_variable_opens_existing_profile_editor_at_exact_target');
  await page.locator('#schedule-template-values input').fill('销售客户');await page.locator('#schedule-template-profile-save').click();await page.waitForFunction(()=>scheduleTemplateRequest===null);await page.locator('#schedule-template-dialog .dialog-heading .close-dialog').click();await page.waitForFunction(({id,version})=>!scheduleBatchEditingTemplate&&scheduleBatchRequest===null&&scheduleBatchTemplates.some(row=>row.id===id&&row.version===version),{id:template.id,version:template.version});
  check((await page.locator('#schedule-batch-template option:checked').innerText()).includes('版本 2')&&(await page.locator('#schedule-batch-count').innerText()).includes('已选择 3')&&await page.locator('#schedule-batch-create').isDisabled(),'profile_save_refreshes_version_preserves_batch_draft_and_requires_preview');await preview();
  state.groups=[...groups,{id:'unrelated-arriving-chat',name:'新出现的无关会话',conversationKind:'direct'}];await refresh();check(await page.locator('#schedule-batch-dialog').isVisible()&&!await page.locator('#schedule-batch-create').isDisabled()&&(await page.locator('#schedule-batch-count').innerText()).includes('已选择 3'),'unrelated_new_conversation_preserves_draft_and_preview');
  groups[0].name='改名后的业务会话';await refresh();check(await page.locator('#schedule-batch-dialog').isVisible()&&await page.locator('#schedule-batch-create').isDisabled()&&(await page.locator('#schedule-batch-count').innerText()).includes('已选择 3'),'selected_target_rename_invalidates_preview_without_losing_selection');await preview();
  const allText=await page.locator('#schedule-batch-results').innerText();check(allText.includes(groups[0].id)&&allText.includes(groups[1].id)&&allText.includes('完整正文覆盖')&&allText.includes('{{保留为文字}}')&&allText.includes('<literal>'),'full_per_target_text_and_literal_override_are_visible_by_stable_id');
  check(allText.includes('首期提交截止')&&allText.includes('窗口 5 分钟')&&(await page.locator('#schedule-batch-summary').innerText()).includes('已有 1 条记录'),'first_run_deadline_and_total_record_capacity_are_explicit');
  await visible('.schedule-batch-record:nth-of-type(1) .schedule-batch-text','desktop_full_message_visible');await page.screenshot({path:'output/playwright/schedule-batch-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});check(await page.locator('#schedule-batch-dialog').evaluate(node=>node.scrollWidth<=node.clientWidth+1),'mobile_batch_dialog_has_no_horizontal_overflow');await visible('#schedule-batch-template','mobile_template_select_reachable');await visible('#schedule-batch-window','mobile_window_input_reachable');await visible(page.locator('.schedule-batch-record').filter({hasText:groups[1].id}).locator('.schedule-batch-text'),'mobile_full_override_visible_without_footer_cover');await page.screenshot({path:'output/playwright/schedule-batch-mobile.png',fullPage:true});await visible('#schedule-batch-create','mobile_final_create_button_reachable');await page.screenshot({path:'output/playwright/schedule-batch-mobile-actions.png',fullPage:true});await page.setViewportSize({width:1440,height:1040});
  await page.locator('#schedule-batch-window').fill('10');check(await page.locator('#schedule-batch-create').isDisabled()&&await page.locator('.schedule-batch-record').count()===0,'calendar_edit_invalidates_complete_preview');await page.locator('#schedule-batch-window').fill('5');
  capacityCount=499;await preview();check(await page.locator('#schedule-batch-create').isDisabled()&&(await page.locator('#schedule-batch-summary').innerText()).includes('499'),'capacity_failure_blocks_batch_without_silent_partial_creation');capacityCount=null;forceDuplicate=true;await preview();check((await page.locator('#schedule-batch-results').innerText()).includes('已有启用或暂停的相同计划')&&await page.locator('#schedule-batch-create').isDisabled(),'existing_matching_active_or_paused_plan_blocks_duplicate_batch');forceDuplicate=false;await preview();
  const requestId=await page.evaluate(()=>scheduleBatchRequestId);forceStale=true;await page.locator('#schedule-batch-create').click();await ready();check((await page.locator('#schedule-batch-message').innerText()).includes('首期时间已变化')&&jobsFor(source.id).length===1&&await page.evaluate(()=>scheduleBatchRequestId)===requestId,'stale_due_conflict_creates_zero_and_keeps_request_identity');await page.locator('#schedule-batch-reload').click();await ready();await preview();
  const held={started:deferred(),done:deferred()};writeGate=held;loseResponse=true;await page.evaluate(()=>{window.__batchCreate=createScheduleBatch();});await held.started.promise;const writes=requests.filter(row=>row.path==='/api/jobs/batch').length;
  check(await page.locator('#new-schedule').isDisabled()&&await page.locator('#schedule-pause-all').isDisabled()&&await page.locator('#schedule-batch-template').isDisabled(),'batch_create_disables_single_creation_pause_and_input_changes');await page.evaluate(()=>{pauseSchedules();openSchedule();createScheduleBatch();});check(requests.filter(row=>row.path==='/api/jobs/batch').length===writes&&!requests.some(row=>row.path==='/api/jobs/pause-all'),'competing_handlers_cannot_send_during_create');held.done.resolve();await page.evaluate(()=>window.__batchCreate);await ready();
  check((await page.locator('#schedule-batch-message').innerText()).includes('未确认本批创建结果')&&await page.locator('#schedule-batch-template').isDisabled()&&!await page.locator('#schedule-batch-create').isDisabled(),'lost_response_keeps_frozen_request_for_explicit_retry');
  const frozen=JSON.stringify(requests.filter(row=>row.path==='/api/jobs/batch').at(-1).body),count=jobsFor(source.id).length;templatesAvailable=false;template.version++;jobsFor(source.id)[1].enabled=false;jobsFor(source.id)[1].state='paused';await close();await open();await page.locator('#schedule-batch-create').click();await ready();
  check(JSON.stringify(requests.filter(row=>row.path==='/api/jobs/batch').at(-1).body)===frozen&&jobsFor(source.id).length===count&&!jobsFor(source.id)[1].enabled&&(await page.locator('#schedule-batch-message').innerText()).includes('已核对原批次：3'),'replay_after_template_change_returns_original_jobs_without_duplicate_or_resume');
  check(await page.locator('#schedule-batch-create').isDisabled()&&await page.locator('#schedule-batch-new').isVisible(),'completed_batch_requires_explicit_new_batch_action');templatesAvailable=true;await page.locator('#schedule-batch-new').click();await ready();await page.locator('#schedule-batch-mode').selectOption('daily');await page.locator('#schedule-batch-clock').fill('10:00');await preview();
  check(!Object.hasOwn(requests.filter(row=>row.path==='/api/jobs/batch/preview').at(-1).body,'weekdays'),'daily_batch_omits_weekdays');
  const late={started:deferred(),done:deferred()};writeGate=late;await page.evaluate(()=>{window.__oldBatch=createScheduleBatch();});await late.started.promise;state.account='batch-account-b';state.runtime.source={...source,id:state.account};await refresh();await open();await choose();await preview();const current={started:deferred(),done:deferred()};writeGate=current;await page.evaluate(()=>{window.__newBatch=createScheduleBatch();});await current.started.promise;late.done.resolve();await page.evaluate(()=>window.__oldBatch);
  check(await page.locator('#schedule-batch-create').isDisabled()&&await page.evaluate(()=>scheduleBusy)&&await page.evaluate(()=>state.jobs.length)===0,'late_old_account_success_cannot_replace_or_unlock_new_batch');current.done.resolve();await page.evaluate(()=>window.__newBatch);await ready();await page.locator('#schedule-batch-new').click();await ready();await page.locator('#schedule-batch-clock').fill('12:00');await preview();
  const failure={started:deferred(),done:deferred(),fail:true};writeGate=failure;await page.evaluate(()=>{window.__oldFailure=createScheduleBatch();});await failure.started.promise;state.account='batch-account-c';state.runtime.source={...source,id:state.account};await refresh();await open();failure.done.resolve();await page.evaluate(()=>window.__oldFailure);check(!(await page.locator('#schedule-batch-message').innerText()).includes('旧账号批次失败'),'late_old_account_failure_does_not_pollute_new_draft');
  await choose();const latePreview={started:deferred(),done:deferred()};previewGate=latePreview;await page.evaluate(()=>{window.__oldPreview=previewScheduleBatch();});await latePreview.started.promise;state.watchedGroups=[groups[2].id];await refresh();latePreview.done.resolve();await page.evaluate(()=>window.__oldPreview);check(await page.evaluate(()=>scheduleBatchPreview===null&&scheduleBatchGroups.size===1)&&await page.locator('#schedule-batch-create').isDisabled(),'selected_reading_scope_change_discards_late_preview_and_keeps_eligible_targets');
  state.runtime.capabilities.scheduleBatches=false;await refresh();check(await page.locator('#schedule-batch-open').isHidden(),'old_service_hides_batch_entry');state.runtime={mode:'demo',capabilities:{canSend:true,scheduleBatches:true}};state.connection={status:'logged_in'};await refresh();check(await page.locator('#schedule-batch-open').isHidden(),'demo_hides_batch_entry');
  check(rule.text==='保留的回复草稿'&&!rule.enabled,'batch_workflow_preserves_existing_reply_rule');check(!requests.some(row=>row.method==='POST'&&!['/api/select','/api/schedule-templates/profile','/api/jobs/batch/preview','/api/jobs/batch'].includes(row.path)),'no_message_hook_single_job_or_rule_mutation');check(errors.length===0,'no_browser_javascript_errors');
  return {checks,realBrowser:true,allApis:'synthetic',realWindowsReadOrSend:false};
 }finally{for(const gate of gates)gate.resolve();page.off('pageerror',onError);await page.unroute('**/api/**',handler);}
}
