// Synthetic DOM and deferred APIs; never starts Hook or contacts a real service.
'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
function node(tag='',cls='',text=''){return {tag,cls,textContent:text,value:'',children:[],hidden:false,disabled:false,checked:false,open:false,events:{},append(...items){this.children.push(...items);},replaceChildren(){this.children=[];this.value='';},addEventListener(event,callback){this.events[event]=callback;},showModal(){this.open=true;},close(){if(this.open){this.open=false;this.events.close?.();}}};}
const nodes=new Map(),$=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);};
const pending=[],calls=[],checks=[];let refreshes=0;
const ctx=vm.createContext({$,el:node,URLSearchParams,serviceAvailable:true,stamp:()=> 'time',state:{account:'a',runtime:{mode:'database',capabilities:{handoffNotifications:true}},watchedGroups:['g1','g2','p1','p2']},
 isDatabase:()=>ctx.state.runtime.mode==='database',handoffScopeKey:()=>JSON.stringify([ctx.state.account,ctx.state.watchedGroups,ctx.state.runtime.mode,ctx.state.runtime.capabilities.handoffNotifications]),
 loadHandoffs:async()=>{refreshes++;},api:(url,body)=>{calls.push({url,body});return new Promise((resolve,reject)=>pending.push({resolve,reject}));}});
const run=code=>vm.runInContext(code,ctx);run(fs.readFileSync(path.join(__dirname,'../static/handoff_notification_ui.js'),'utf8'));
const config=(groupId='g1',targetId='',enabled=false,version=0,routeVersion=1)=>({groupId,groupName:'同名群',owner:'销售 · 张明',routeVersion,version,enabled,targetId,targetName:targetId?'同名联系人':'',issue:'',updatedAt:version?100:null});
const recipients=[{id:'p1',name:'同名联系人'},{id:'p2',name:'同名联系人'}];
async function open(configs=[config(),config('g2')],targets=recipients){const promise=run('openHandoffNotifications()');pending.shift().resolve({configs,recipients:targets});await promise;}
function check(name,fn){fn();checks.push(name);}
const text=node=>node.textContent+node.children.map(text).join(' ');
(async()=>{
 await open();check('no_automatic_recipient_or_enable_selection',()=>{assert.equal($('handoff-notify-target').value,'');assert.equal($('handoff-notify-enabled').checked,false);assert.equal($('handoff-notify-enabled').disabled,true);});
 check('same_name_recipient_ids_and_group_ids_are_visible',()=>{assert.deepEqual($('handoff-notify-target').children.map(item=>item.textContent),['选择已读取的接收私聊','同名联系人 · p1','同名联系人 · p2']);assert.equal($('handoff-notify-group').children[1].textContent,'同名群 · g2');});
 $('handoff-notify-target').value='p2';$('handoff-notify-target').onchange();$('handoff-notify-enabled').checked=true;run('updateHandoffNotificationScope()');check('poll_preserves_selected_recipient_and_explicit_enable',()=>{assert.equal($('handoff-notify-target').value,'p2');assert.equal($('handoff-notify-enabled').checked,true);});
 check('example_shows_group_identity_and_explicit_recipient',()=>{assert.match($('handoff-notify-example').textContent,/p2/);assert.match($('handoff-notify-example').textContent,/g1/);assert.match($('handoff-notify-example').textContent,/提醒不代表已领取或完成/);});
 let saving=run('saveHandoffNotifications()');check('save_binds_config_and_route_versions_with_exact_target',()=>assert.equal(JSON.stringify(calls.at(-1).body),JSON.stringify({account:'a',groupId:'g1',version:0,routeVersion:1,targetId:'p2',enabled:true})));pending.shift().resolve(config('g1','p2',true,1));await saving;
 check('enable_does_not_backfill_old_tasks',()=>{assert.match($('handoff-notify-message').textContent,/不补发已有待办/);assert.equal(refreshes,1);});
 $('handoff-notify-target').value='p1';$('handoff-notify-target').onchange();check('changing_recipient_requires_new_explicit_enable',()=>assert.equal($('handoff-notify-enabled').checked,false));
 $('handoff-notify-enabled').checked=true;saving=run('saveHandoffNotifications()');const count=calls.length;pending.shift().reject(Object.assign(Error('route changed'),{status:409}));await saving;run('updateHandoffNotificationScope()');
 check('cas_conflict_keeps_target_and_enable_draft_without_reload',()=>{assert.equal(calls.length,count);assert.equal($('handoff-notify-target').value,'p1');assert.equal($('handoff-notify-enabled').checked,true);assert.equal($('handoff-notify-save').disabled,true);assert.match($('handoff-notify-message').textContent,/409/);});
 let loading=run('loadHandoffNotifications()');pending.shift().resolve({configs:[{...config('g1','p2',false,2,2),issue:'负责人已变化，请重新核对'}],recipients});await loading;
 check('explicit_reload_shows_owner_change_disabled_configuration',()=>{assert.equal($('handoff-notify-enabled').checked,false);assert.match($('handoff-notify-current').textContent,/负责人已变化/);assert.equal(run('handoffNotifyConfig.routeVersion'),2);});
 await open([config('g1','removed',false,3)],recipients);check('invalid_saved_recipient_is_displayed_without_replacement',()=>{assert.equal($('handoff-notify-target').value,'removed');assert.equal($('handoff-notify-target').children.at(-1).disabled,true);assert.equal($('handoff-notify-enabled').disabled,true);});
 saving=run('saveHandoffNotifications()');check('disabled_configuration_preserves_invalid_original_target',()=>{assert.equal(calls.at(-1).body.targetId,'removed');assert.equal(calls.at(-1).body.enabled,false);});pending.shift().resolve(config('g1','removed',false,4));await saving;
 await open([config('g1','p1',true,5)]);$('handoff-notify-enabled').checked=false;saving=run('saveHandoffNotifications()');pending.shift().resolve(config('g1','p1',false,6));await saving;check('disable_explains_cancellation_and_inflight_limit',()=>{assert.match($('handoff-notify-message').textContent,/取消尚未尝试/);assert.match($('handoff-notify-message').textContent,/仍可能提交/);});
 $('handoff-notify-enabled').checked=true;saving=run('saveHandoffNotifications()');const old=pending.shift();ctx.state.account='b';run('updateHandoffNotificationScope()');await open([config('g1','p2')]);$('handoff-notify-enabled').checked=true;const newer=run('saveHandoffNotifications()'),latest=pending.shift();old.resolve(config('g1','p1',true,7));await saving;
 check('old_account_result_cannot_overwrite_or_unlock_new_request',()=>{assert.equal($('handoff-notify-target').value,'p2');assert.equal($('handoff-notify-save').disabled,true);});latest.resolve(config('g1','p2',true,1));await newer;
 loading=run('loadHandoffNotifications()');const late=pending.shift();ctx.state.watchedGroups=['g1'];run('updateHandoffNotificationScope()');late.resolve({configs:[config('g1','p2',true,2)],recipients});await loading;check('recipient_read_scope_change_closes_and_discards_late_load',()=>{assert.equal($('handoff-notification-dialog').open,false);assert.equal($('handoff-notify-target').value,'');assert.equal(run('handoffNotifyConfig'),null);});
 for(const status of ['unassigned','not_configured','queued','cancelled','expired','blocked','unknown','submitted_unconfirmed','server_accepted','local_record_observed','local_record_confirmed']){
  ctx.fixture={notification:{status,issue:'合成状态说明',targetId:'p1',targetName:'同名联系人',createdAt:10,expiresAt:610,draftId:'synthetic-draft',delivered:false,retryAllowed:false}};run('renderHandoffNotificationDetail(fixture)');assert.equal($('handoff-notification-detail').hidden,false);assert.doesNotMatch(text($('handoff-notification-detail')),/undefined/);assert.match(text($('handoff-notification-detail')),/不能证明负责人已收到/);
 }checks.push('all_notification_states_keep_delivery_evidence_separate');
 check('unknown_state_explicitly_disallows_automatic_retry',()=>assert.match(run('handoffNotificationSummary({status:"unknown"})'),/不自动重试/));
 ctx.state.runtime.capabilities.handoffNotifications=false;run('updateHandoffNotificationScope();renderHandoffNotificationDetail({})');check('old_service_hides_notification_ui_without_reading_new_dto',()=>{assert.equal($('handoff-notification-open').hidden,true);assert.equal($('handoff-notification-detail').hidden,true);});
 ctx.state.runtime.capabilities.handoffNotifications=true;ctx.state.runtime.mode='demo';run('updateHandoffNotificationScope()');check('demo_hides_automatic_notification_configuration',()=>assert.equal($('handoff-notification-open').hidden,true));
 check('configuration_calls_never_send_or_change_group_rules',()=>assert.ok(calls.every(call=>!call.body||call.url==='/api/handoffs/notifications')));
 console.log('PASS: '+checks.length+' handoff notification controls checks (synthetic only)');
})().catch(error=>{console.error(error);process.exitCode=1;});
