// Synthetic DOM and deferred APIs. No real backend, WeChat or Hook.
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
function node(tag='div',cls='',text=''){return {tag,cls,textContent:text,value:'',children:[],hidden:false,disabled:false,open:false,events:{},append(...items){this.children.push(...items);},replaceChildren(...items){this.children=items;},querySelectorAll(selector){return this.children.flatMap(child=>[...(child.tag===selector?[child]:[]),...child.querySelectorAll(selector)]);},addEventListener(event,fn){(this.events[event]??=[]).push(fn);},showModal(){this.open=true;},close(){if(this.open){this.open=false;for(const fn of this.events.close||[])fn();}}};}
const nodes=new Map(),$=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},calls=[],pending=[],checks=[];let serial=0;
const ctx=vm.createContext({$,el:node,URLSearchParams,Date,JSON,crypto:{randomUUID:()=> 'card-fixture-'+(++serial)},state:{account:'a',runtime:{mode:'database',source:{id:'source-a'},capabilities:{approvedReplies:true}},groups:[{id:'g1',name:'同名群',conversationKind:'group'},{id:'g2',name:'同名群',conversationKind:'group'}]},selected:'g1',serviceAvailable:true,replyBusy:false,replyDirty:false,
 isDatabase:()=>ctx.state.runtime.mode==='database',isDemo:()=>false,groupName:id=>id,controls:()=>run('updateApprovedReplyScope()'),stamp:()=> 'time',emptyCard:()=>node(),setView:()=>{},selectGroup:()=>{},toast:()=>{},
 document:{hidden:false},setTimeout,clearTimeout,api:(url,body)=>{calls.push({url,body:body===undefined?undefined:JSON.parse(JSON.stringify(body))});return new Promise((resolve,reject)=>pending.push({resolve,reject}));}});
const run=code=>vm.runInContext(code,ctx),read=file=>fs.readFileSync(path.join(__dirname,'../static/'+file),'utf8');run(read('approved_reply_ui.js'));
const card=()=>({id:'card-fixture-original',name:'价格问答',questions:['@工作台 价格？\n请回答'],sourceTitle:'批准资料',sourceVersion:'v1',sourceText:'资料全文\n只讨论批准内容',replyText:'批准的完整回复'});
const policy=(version=0,groupId=ctx.selected)=>({account:ctx.state.account,groupId,version,enabled:false,mode:'handoff',cooldown:30,cards:[card()],issue:'',sendingPaused:false});
async function open(dto=policy()){const p=run('openApprovedReply()');if(pending.length)pending.shift().resolve(dto);await p;}
const output=n=>n.textContent+n.children.map(output).join(' '),check=(name,fn)=>{fn();checks.push(name);};
(async()=>{
 await open();check('existing_mode_and_separate_approval_boundary_visible',()=>{assert.match($('approved-policy-state').textContent,/人工待办/);assert.match($('approved-policy-state').textContent,/保存草稿不改变/);assert.equal($('approved-questions').querySelectorAll('textarea')[0].value,'@工作台 价格？\n请回答');});
 $('approved-source-text').value='尚未保存的资料全文';$('approved-source-text').oninput();run('updateApprovedReplyScope()');check('ordinary_poll_preserves_policy_draft',()=>assert.equal($('approved-source-text').value,'尚未保存的资料全文'));
 $('approved-question-add').onclick();const questions=$('approved-questions').querySelectorAll('textarea');questions[1].value='另一条\n完整问法';questions[1].oninput();check('multiline_questions_remain_separate_whole_messages',()=>assert.deepEqual([...run('approvedReplyCards[0].questions')],['@工作台 价格？\n请回答','另一条\n完整问法']));
 $('approved-preview-input').value='@工作台 价格？\n请回答';let preview=run('previewApprovedReply()');pending.shift().resolve({decision:'reply',reasonCode:'matched',reason:'整条问法匹配',matchedCard:card(),replyText:'批准的完整回复',policyVersion:0});await preview;
 check('preview_shows_literal_reply_and_no_real_mention_or_send_claim',()=>{assert.match(output($('approved-preview-result')),/批准的完整回复/);assert.match(output($('approved-preview-result')),/没有验证真实 @/);assert.equal(calls.at(-1).url,'/api/reply/policy/preview');});
 preview=run('previewApprovedReply()');const late=pending.shift();$('approved-reply-text').value='修改后的回复';$('approved-reply-text').oninput();late.resolve({decision:'reply',reasonCode:'matched',reason:'匹配',matchedCard:card(),replyText:'迟到旧回复',policyVersion:0});await preview;check('edited_draft_discards_late_preview',()=>assert.doesNotMatch(output($('approved-preview-result')),/迟到旧回复/));
 let saving=run('saveApprovedReply(false)');check('save_draft_posts_false_and_exact_policy_version',()=>{assert.equal(calls.at(-1).body.enabled,false);assert.equal(calls.at(-1).body.version,0);assert.equal(ctx.replyBusy,true);assert.equal($('approved-source-text').disabled,true);});pending.shift().resolve(policy(1));await saving;
 check('draft_save_preserves_old_mode_in_returned_policy',()=>{assert.equal(run('approvedReplyPolicy.mode'),'handoff');assert.match($('approved-message').textContent,/原固定回复或人工待办规则保持不变/);});
 saving=run('saveApprovedReply(true)');pending.shift().resolve({...policy(2),mode:'approved',enabled:true});await saving;check('explicit_approval_uses_new_endpoint_and_true_flag',()=>{assert.equal(calls.at(-1).body.enabled,true);assert.equal(calls.at(-1).url,'/api/reply/policy');assert.match($('approved-message').textContent,/已批准并启用/);});
 $('approved-source-text').value='冲突时保留资料';$('approved-source-text').oninput();saving=run('saveApprovedReply(true)');pending.shift().reject(Object.assign(Error('changed'),{status:409}));await saving;const count=calls.length;run('updateApprovedReplyScope()');check('cas_conflict_retains_draft_blocks_resave_and_never_auto_reloads',()=>{assert.equal($('approved-source-text').value,'冲突时保留资料');assert.equal($('approved-enable').disabled,true);assert.match($('approved-message').textContent,/409/);assert.equal(calls.length,count);});
 let loading=run('loadApprovedReply()');pending.shift().resolve({...policy(3),mode:'approved',enabled:true,sendingPaused:true,issue:'发送已暂停'});await loading;check('explicit_reload_shows_sending_pause_with_intake_continuing',()=>assert.match($('approved-policy-state').textContent,/读取处理继续/));
 $('approved-source-text').value='离线编辑草稿';$('approved-source-text').oninput();ctx.serviceAvailable=false;run('updateApprovedReplyScope()');$('approved-reply-dialog').close();await run('openApprovedReply()');check('service_offline_preserves_viewable_editable_draft_and_blocks_network_actions',()=>{assert.equal($('approved-source-text').value,'离线编辑草稿');assert.equal($('approved-source-text').disabled,false);assert.equal($('approved-save-draft').disabled,true);});ctx.serviceAvailable=true;run('approvedReplyControls()');
 loading=run('loadApprovedReply()');const oldRead=pending.shift();$('approved-source-title').value='重读期间的新编辑';$('approved-source-title').oninput();oldRead.resolve(policy(4));await loading;check('late_reload_cannot_overwrite_new_editor_input',()=>assert.equal($('approved-source-title').value,'重读期间的新编辑'));
 saving=run('saveApprovedReply(false)');const oldWrite=pending.shift();ctx.state.account='b';ctx.state.runtime.source.id='source-b';run('updateApprovedReplyScope()');await open();const newer=run('saveApprovedReply(true)'),newWrite=pending.shift();oldWrite.resolve(policy(99));await saving;check('old_account_success_cannot_unlock_or_replace_new_write',()=>{assert.equal(ctx.replyBusy,true);assert.equal($('approved-enable').disabled,true);assert.equal(run('approvedReplyPolicy.version'),0);});newWrite.resolve({...policy(1),mode:'approved',enabled:true});await newer;
 preview=run('previewApprovedReply()');const groupLate=pending.shift();ctx.selected='g2';run('updateApprovedReplyScope()');groupLate.reject(Error('旧群错误'));await preview;check('group_change_closes_dialog_and_discards_late_failure',()=>{assert.equal($('approved-reply-dialog').open,false);assert.doesNotMatch($('approved-message').textContent,/旧群错误/);});
 await open({...policy(0),cards:[]});check('empty_card_draft_can_save_but_cannot_enable',()=>{assert.equal($('approved-save-draft').disabled,false);assert.equal($('approved-enable').disabled,true);});run('addApprovedReplyCard()');check('new_card_uses_stable_id_and_one_whole_question',()=>{assert.match(run('approvedReplyCards[0].id'),/card-fixture-/);assert.equal($('approved-questions').querySelectorAll('textarea').length,1);});
 const app=read('app.js');run(app.slice(app.indexOf("$('reply-form').onsubmit="),app.indexOf("for(const id of ['reply-enabled'")));$('reply-mode').value='approved';$('save-reply').disabled=false;const before=calls.length;await $('reply-form').onsubmit({preventDefault(){}});check('main_approved_save_never_calls_legacy_reply_api',()=>assert.equal(calls.length,before));
 run(read('execution_ui.js'));ctx.audit={id:'audit-1',targetName:'群',targetId:'g2',label:'本机待办',source:'reply',decision:'handoff',text:'',textUnavailable:false,createdAt:1,timeBasis:'触发时间',issue:'未知问法转人工',reasonCode:'unmatched',approvedPolicy:{version:7,card:card()}};run('executionRows=[audit];renderExecutionHistory()');
 check('execution_history_renders_frozen_card_material_and_reply_instead_of_json_only',()=>{const text=output($('execution-list'));for(const value of ['策略版本 7','card-fixture-original','批准资料','v1','资料全文','批准的完整回复','unmatched','未知问法转人工'])assert.ok(text.includes(value),value);});
 ctx.audit={...ctx.audit,reasonCode:'submission_unknown',issue:'发送结果未知'};run('executionRows=[audit];renderExecutionHistory()');check('unknown_submission_handoff_does_not_claim_no_reply_was_sent',()=>{const text=output($('execution-list'));assert.ok(text.includes('提交结果未知，请核对微信记录后处理，勿直接重发。'));assert.doesNotMatch(text,/本条未发送回复/);});
 ctx.state.runtime.capabilities.approvedReplies=false;run('updateApprovedReplyScope()');ctx.audit={...ctx.audit};delete ctx.audit.approvedPolicy;delete ctx.audit.reasonCode;run('executionRows=[audit];executionRenderKey="";renderExecutionHistory()');check('old_service_hides_option_and_accepts_legacy_history',()=>{assert.equal($('reply-approved-option').hidden,true);assert.doesNotMatch(output($('execution-list')),/批准依据/);});ctx.state.runtime.capabilities.approvedReplies=true;ctx.state.runtime.mode='demo';run('updateApprovedReplyScope()');check('demo_hides_approved_mode',()=>assert.equal($('reply-approved-option').hidden,true));
 check('all_writes_are_policy_save_or_pure_preview',()=>assert.ok(calls.every(call=>!call.body||['/api/reply/policy','/api/reply/policy/preview'].includes(call.url))));
 console.log('PASS: '+checks.length+' approved reply controls checks (synthetic only)');
})().catch(error=>{console.error(error);process.exitCode=1;});
