// Synthetic DOM and deferred APIs. No real service or native sending.
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../static/schedule_template_ui.js'),'utf8');
function node(tag='div'){return {tag,children:[],value:'',textContent:'',hidden:false,disabled:false,checked:false,dataset:{},events:{},append(...items){this.children.push(...items);},replaceChildren(){this.children=[];},querySelectorAll(selector){return this.children.flatMap(child=>[...(child.tag===selector?[child]:[]),...child.querySelectorAll(selector)]);},addEventListener(event,fn){this.events[event]=fn;},showModal(){this.open=true;},close(){if(this.open){this.open=false;this.events.close?.();}},focus(){this.focused=true;}};}
const nodes=new Map(),$=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},pending=[],requests=[],checks=[];
const context=vm.createContext({$,URLSearchParams,crypto:{randomUUID:()=> 'new-template'},el:(tag,cls,text)=>Object.assign(node(tag),{textContent:text||''}),serviceAvailable:true,scheduleBusy:false,schedulePauseRequest:null,scheduleRequestId:'task-draft',scheduleBatchTemplateChanged:()=>{},
 state:{account:'a',groups:[{id:'g1',name:'同名群'},{id:'g2',name:'同名群'}],runtime:{mode:'database',source:{id:'a'},capabilities:{scheduleTemplates:true}}},isDatabase:()=>context.state.runtime.mode==='database',
 api:(url,body)=>{requests.push({url,body});return new Promise((resolve,reject)=>pending.push({resolve,reject}));}});
vm.runInContext(source,context);const run=code=>vm.runInContext(code,context);
function detail(group='g1',version=1){return {id:'t1',name:'提醒',text:'{{客户}}您好',version,variables:['客户'],targets:[{groupId:'saved',targetName:'已移出源的群'}],groupId:group,profile:{values:{客户:group==='g1'?'甲':'乙'},overrideText:null}};}
function show(mode='manage'){run('updateScheduleTemplateScope()');$('schedule-template-dialog').showModal();context.fixture=detail();run('scheduleTemplateMode="'+mode+'";renderScheduleTemplateDetail(fixture)');$('schedule-template-select').value='t1';}
function check(name,fn){fn();checks.push(name);}
async function previewResult(text='甲您好'){const request=run('previewScheduleTemplate()');pending.shift().resolve({id:'t1',version:1,groupId:$('schedule-template-target').value,templateName:'提醒',text});await request;}
(async()=>{
 show();check('same_name_targets_show_distinct_ids_and_saved_profiles',()=>assert.deepEqual($('schedule-template-target').children.map(row=>row.textContent),['选择会话','同名群 · g1','同名群 · g2','已移出源的群 · saved']));
 context.fixture={...detail(),text:'{{__proto__}}',variables:['__proto__'],profile:{values:Object.fromEntries([['__proto__','合法变量值']]),overrideText:null}};run('renderScheduleTemplateDetail(fixture)');
 check('prototype_named_variable_survives_profile_json',()=>{const serialized=JSON.parse(JSON.stringify(run('scheduleTemplateProfile()')));assert.equal(Object.hasOwn(serialized.values,'__proto__'),true);assert.equal(serialized.values.__proto__,'合法变量值');});
 await previewResult('合法变量值');check('preview_request_contains_prototype_named_variable',()=>assert.equal(JSON.parse(JSON.stringify(requests.at(-1).body)).values.__proto__,'合法变量值'));
 context.fixture=detail();run('renderScheduleTemplateDetail(fixture)');
 await previewResult();check('manager_preview_never_offers_apply',()=>assert.equal($('schedule-template-apply').hidden,true));
 const late=run('previewScheduleTemplate()'),lateReply=pending.shift();const variable=$('schedule-template-values').querySelectorAll('input')[0];variable.value='新草稿';variable.oninput();lateReply.resolve({id:'t1',version:1,groupId:'g1',templateName:'提醒',text:'旧正文'});await late;
 check('late_preview_cannot_replace_edited_variable_draft',()=>{assert.equal($('schedule-template-preview-text').textContent,'');assert.equal(variable.value,'新草稿');assert.equal($('schedule-template-apply').disabled,true);});
 const oldTarget=run('loadScheduleTemplate("t1","g1")'),oldTargetReply=pending.shift();const newTarget=run('loadScheduleTemplate("t1","g2")'),newTargetReply=pending.shift();newTargetReply.resolve(detail('g2'));await newTarget;oldTargetReply.resolve(detail('g1'));await oldTarget;
 check('late_target_detail_cannot_replace_new_target',()=>{assert.equal($('schedule-template-target').value,'g2');assert.equal($('schedule-template-values').querySelectorAll('input')[0].value,'乙');});
 $('schedule-template-override').checked=true;$('schedule-template-override').onchange();$('schedule-template-override-text').value='';const empty=run('previewScheduleTemplate()');pending.shift().reject(Error('覆盖正文不能为空'));await empty;
 check('empty_override_is_not_replaced_with_template_or_applied',()=>{assert.equal(requests.at(-1).body.overrideText,'');assert.equal($('schedule-template-apply').disabled,true);assert.match($('schedule-template-message').textContent,/不能为空/);});
 $('schedule-template-name').value='未保存名称';$('schedule-template-name').oninput();const conflict=run('mutateScheduleTemplate("save")');pending.shift().reject(Object.assign(Error('changed'),{status:409}));await conflict;
 check('conflict_keeps_draft_and_requires_explicit_reload',()=>{assert.equal($('schedule-template-name').value,'未保存名称');assert.match($('schedule-template-message').textContent,/409/);assert.equal($('schedule-template-save').disabled,true);assert.equal($('schedule-template-reload').disabled,false);});
 const reload=run('loadScheduleTemplate("t1","g1")');pending.shift().resolve(detail('g1',2));await reload;check('explicit_reload_accepts_new_version',()=>assert.equal(run('scheduleTemplateDetail.version'),2));
 const accountLate=run('previewScheduleTemplate()'),accountReply=pending.shift();context.state={...context.state,account:'b',runtime:{...context.state.runtime,source:{id:'b'}}};run('updateScheduleTemplateScope()');accountReply.resolve({id:'t1',version:2,groupId:'g1',templateName:'old account',text:'旧账号正文'});await accountLate;
 check('account_change_closes_dialog_and_discards_late_preview',()=>{assert.equal($('schedule-template-dialog').open,false);assert.equal($('schedule-template-preview-text').textContent,'');});
 show('apply');$('schedule-dialog').showModal();$('schedule-group').value='g1';$('schedule-text').value='原草稿';run('scheduleTemplateApplyContext={account:state.account,groupId:"g1",requestId:scheduleRequestId,text:"原草稿"}');await previewResult();
 const before=requests.length;run('applyScheduleTemplate()');check('apply_only_copies_literal_text_without_creating_or_sending',()=>{assert.equal($('schedule-text').value,'甲您好');assert.equal(requests.length,before);assert.equal($('schedule-template-dialog').open,false);});
 $('schedule-group').value='g2';run('scheduleTemplateTargetChanged()');check('unchanged_generated_text_cleared_on_target_change',()=>assert.equal($('schedule-text').value,''));
 show('apply');$('schedule-group').value='g1';run('scheduleTemplateApplyContext={account:state.account,groupId:"g1",requestId:scheduleRequestId,text:""}');await previewResult();run('applyScheduleTemplate()');$('schedule-text').value='人工修改';$('schedule-text').events.input();$('schedule-group').value='g2';run('scheduleTemplateTargetChanged()');check('manual_text_survives_target_change',()=>assert.equal($('schedule-text').value,'人工修改'));
 show('apply');$('schedule-group').value='g1';run('scheduleTemplateApplyContext={account:state.account,groupId:"g1",requestId:scheduleRequestId,text:"人工修改"}');await previewResult();$('schedule-text').value='较新草稿';run('applyScheduleTemplate()');check('changed_task_draft_cannot_be_overwritten_by_preview',()=>{assert.equal($('schedule-text').value,'较新草稿');assert.equal($('schedule-template-apply').disabled,true);});
 const closing=run('previewScheduleTemplate()'),closeReply=pending.shift();$('schedule-template-dialog').close();closeReply.resolve({id:'t1',version:1,groupId:'g1',templateName:'提醒',text:'关闭后的旧预览'});await closing;check('closed_dialog_discards_late_response',()=>assert.equal($('schedule-template-preview-text').textContent,''));
 context.state.runtime.capabilities.scheduleTemplates=false;run('updateScheduleTemplateScope()');check('old_capability_hides_entries',()=>assert.equal($('schedule-template-library').hidden,true));
 context.state.runtime.capabilities.scheduleTemplates=true;context.state.runtime.mode='demo';run('updateScheduleTemplateScope()');check('demo_hides_entries_even_with_capability',()=>assert.equal($('schedule-template-fill').hidden,true));
 console.log('PASS: '+checks.length+' schedule template controls checks (synthetic only)');
})().catch(error=>{console.error(error);process.exitCode=1;});
