// playwright-cli run-code --filename web_mvp/diagnostics/check_approved_reply_ui.js
// All APIs are mocked. No WeChat database, native Hook, real messages or live backend.
async (page) => {
 const checks=[],errors=[],requests=[],gates=[];
 const check=(value,name)=>{if(!value)throw Error(name);checks.push(name);},clone=value=>JSON.parse(JSON.stringify(value));
 const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);const gate={promise,resolve};gates.push(gate);return gate;};
 const groups=[{id:'approved-alpha@chatroom',name:'同名业务群',conversationKind:'group'},{id:'approved-beta@im.chatroom',name:'同名业务群',conversationKind:'group'}];
 const source={id:'approved-account-a',revision:'r1',status:'snapshot_ready',createdAt:'2026-10-04T01:00:00Z',updatePolicy:'on_change'};
 const state={account:source.id,selfId:'synthetic-self',name:'合成批准账号',csrfToken:'synthetic',connection:{status:'snapshot_ready'},groups,selected:groups[0].id,watchedGroups:groups.map(row=>row.id),jobs:[],outbox:[],runtime:{mode:'database',connected:true,platform:'Windows',source,capabilities:{read:true,canSend:false,hookSendInterface:false,groupSend:false,automaticReplies:true,approvedReplies:true,scheduledSend:true,mentions:true,media:false}}};
 const question='@工作台 报价范围？\n请说明',answer='仅按当前批准资料提供范围说明；订单、价格承诺与时效请由负责人核对。',material='批准资料全文：本卡只解释既定资料范围。\n不自动报价，不承诺库存、订单或完成时效。\n超出该范围交人工处理。';
 const fixtureCard={id:'fixture-card-stable-0001',name:'范围说明',questions:[question],sourceTitle:'产品范围批准资料',sourceVersion:'2026-v1',sourceText:material,replyText:answer};
 const policies=new Map(),rules=new Map(),records=[];let forceConflict=false,previewGate=null,writeGate=null;
 const key=(account,group)=>account+'|'+group;
 function policyFor(account,groupId){const id=key(account,groupId);if(!policies.has(id))policies.set(id,{account,groupId,version:0,cooldown:30,cards:account===source.id?[]:[clone(fixtureCard)],issue:'',sendingPaused:false});return policies.get(id);}
 function ruleFor(account,groupId){const id=key(account,groupId);if(!rules.has(id))rules.set(id,{enabled:true,mode:'reply',text:'原固定回复保留',cooldown:30});return rules.get(id);}
 const dto=(account,groupId)=>{const policy=policyFor(account,groupId),rule=ruleFor(account,groupId);return {...policy,mode:rule.mode,enabled:rule.mode==='approved'&&rule.enabled};};
 const normalize=text=>text.replace(/\r\n/g,'\n').trim();
 function validate(cards){const questions=new Set();for(const card of cards){if(!card.name||!card.sourceTitle||!card.sourceVersion||!card.sourceText||!card.replyText||!card.questions.length||card.questions.some(text=>!normalize(text)))return '卡片字段须填写完整';for(const text of card.questions){const normalized=normalize(text);if(questions.has(normalized))return '完整问法规范化后重复';questions.add(normalized);}}return '';}
 const handler=async response=>{
  const request=response.request(),raw=request.url(),path=raw.split('?')[0].replace(/^https?:\/\/[^/]+/,''),query=Object.fromEntries((raw.split('?')[1]||'').split('&').filter(Boolean).map(part=>{const [name,value='']=part.split('=');return [decodeURIComponent(name),decodeURIComponent(value.replace(/\+/g,' '))];})),body=request.method()==='POST'?request.postDataJSON():null;requests.push({path,query,body,method:request.method()});
  if(path==='/api/state')return response.fulfill({json:state});
  if(path==='/api/database')return response.fulfill({json:{mode:'database',configured:true,busy:false,config:{sourceRoot:'D:\\Synthetic\\db',autoRefresh:true},source:state.runtime.source}});
  if(path==='/api/select'){state.selected=body.groupId;return response.fulfill({json:{ok:true}});}
  if(path==='/api/group'||path==='/api/messages'){const rule=ruleFor(query.account,query.groupId),policy=policyFor(query.account,query.groupId);return response.fulfill({json:{watching:true,members:[],messages:[],outbox:[],reply:{...rule,...(rule.mode==='approved'?{policyVersion:policy.version,sendingPaused:policy.sendingPaused}:{})}}});}
  if(path==='/api/windows/hook/status')return response.fulfill({json:{available:false,status:'disabled',issue:'合成检查不连接 Hook'}});
  if(path==='/api/reply/policy'){
   if(!body)return response.fulfill({json:dto(query.account,query.groupId)});
   const policy=policyFor(body.account,body.groupId),rule=ruleFor(body.account,body.groupId);
   if(forceConflict){forceConflict=false;policy.version++;policy.cards=[{...clone(fixtureCard),name:'并发保存的卡片'}];return response.fulfill({status:409,json:{code:'policy_conflict',error:'策略版本已变化'}});}
   if(body.version!==policy.version)return response.fulfill({status:409,json:{code:'policy_conflict',error:'策略版本已变化'}});
   const error=validate(body.cards);if(error||body.enabled&&!body.cards.length)return response.fulfill({status:400,json:{error:error||'启用至少需要一张卡片'}});
   const held=writeGate;writeGate=null;if(held){held.started.resolve();await held.done.promise;if(held.fail)return response.fulfill({status:409,json:{error:'旧账号策略失败',code:'policy_conflict'}});}
   policy.cards=clone(body.cards);policy.cooldown=body.cooldown;policy.version++;policy.sendingPaused=false;
   if(body.enabled)Object.assign(rule,{mode:'approved',enabled:true,cooldown:body.cooldown});else if(rule.mode==='approved')rule.enabled=false;
   return response.fulfill({json:dto(body.account,body.groupId)});
  }
  if(path==='/api/reply/policy/preview'){
   const policy=policyFor(body.account,body.groupId);if(body.version!==policy.version)return response.fulfill({status:409,json:{code:'policy_conflict',error:'策略版本已变化'}});
   const error=validate(body.cards);if(error)return response.fulfill({status:400,json:{error}});
   const matched=body.cards.find(card=>card.questions.some(question=>normalize(question)===normalize(body.text))),result={decision:matched?'reply':'handoff',reasonCode:matched?'matched':'unmatched',reason:matched?'完整问法匹配到已批准回复':'没有完整问法匹配，转人工',matchedCard:matched?clone(matched):null,replyText:matched?matched.replyText:'',policyVersion:policy.version};
   const held=previewGate;previewGate=null;if(held){held.started.resolve();await held.done.promise;}return response.fulfill({json:result});
  }
  if(path==='/api/execution-history')return response.fulfill({json:{records,limit:200,hasMore:false,nextCursor:'',truncated:false}});
  return response.fulfill({status:400,json:{error:'Synthetic test blocks this API.'}});
 };
 const onError=error=>errors.push(error.message);page.on('pageerror',onError);await page.route('**/api/**',handler);
 const ready=()=>page.waitForFunction(()=>approvedReplyRequest===null),refresh=async()=>{await page.waitForFunction(()=>!pollBusy);await page.evaluate(()=>poll());};
 const open=async()=>{await page.locator('#reply-tab').click();await page.locator('#reply-mode').selectOption('approved');await page.locator('#save-reply').click();await ready();};
 const close=async()=>{await page.locator('#approved-reply-dialog .dialog-heading .close-dialog').click();await page.waitForFunction(()=>!document.getElementById('approved-reply-dialog').open&&approvedReplyPreview===null);};
 const preview=async(text)=>{await page.locator('#approved-preview-input').fill(text);await page.locator('#approved-preview-button').click();await ready();};
 const visible=async(selector,name)=>{const locator=typeof selector==='string'?page.locator(selector):selector;await locator.scrollIntoViewIfNeeded();const ok=await locator.evaluate(node=>{const r=node.getBoundingClientRect(),d=node.closest('dialog')?.getBoundingClientRect(),top=d?Math.max(d.top,0):0,bottom=d?Math.min(d.bottom,innerHeight):innerHeight,hit=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return r.width>0&&r.height>0&&r.top>=top&&r.bottom<=bottom+1&&r.left>=0&&r.right<=innerWidth+1&&!!hit&&(hit===node||node.contains(hit));});check(ok,name);};
 try{
  await page.setViewportSize({width:1440,height:1040});await page.reload();await page.waitForFunction(()=>document.getElementById('selected-name').textContent.includes('同名业务群'));await open();
  check(await page.locator('#reply-text').isDisabled()&&await page.locator('#reply-enabled').isDisabled()&&await page.locator('#reply-cooldown').isDisabled()&&!requests.some(row=>row.path==='/api/reply'),'approved_mode_cannot_be_enabled_through_legacy_controls_or_api');
  check((await page.locator('#approved-policy-state').innerText()).includes(groups[0].id)&&(await page.locator('#approved-policy-state').innerText()).includes('保存草稿不改变该规则')&&await page.locator('#approved-enable').isDisabled(),'exact_group_identity_and_explicit_switch_boundary_visible');
  await page.locator('#approved-card-add').click();await page.locator('#approved-card-name').fill('范围说明');await page.locator('#approved-questions textarea').fill(question);await page.locator('#approved-source-title').fill(fixtureCard.sourceTitle);await page.locator('#approved-source-version').fill(fixtureCard.sourceVersion);await page.locator('#approved-source-text').fill(material);await page.locator('#approved-reply-text').fill(answer);await page.locator('#approved-cooldown').fill('60');await refresh();
  check(await page.locator('#approved-source-text').inputValue()===material&&await page.locator('#approved-questions textarea').inputValue()===question,'ordinary_poll_preserves_complete_policy_editor_draft');
  await preview(' \r\n'+question+' \r\n');check((await page.locator('#approved-preview-result').innerText()).includes(answer)&&(await page.locator('#approved-preview-result').innerText()).includes('没有验证真实 @'),'whole_multiline_question_preview_has_literal_reply_and_no_send_claim');
  await preview('价格？');check((await page.locator('#approved-preview-result').innerText()).includes('将转人工'),'substring_or_missing_display_at_text_does_not_match');await preview(question);
  check(policyFor(source.id,groups[0].id).version===0&&ruleFor(source.id,groups[0].id).mode==='reply','preview_does_not_save_policy_or_switch_existing_rule');
  await visible('#approved-preview-result .approved-full-text','desktop_complete_preview_reply_visible');await page.screenshot({path:'output/playwright/approved-reply-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});check(await page.locator('#approved-reply-dialog').evaluate(node=>node.scrollWidth<=node.clientWidth+1),'mobile_editor_has_no_horizontal_overflow');await visible('#approved-source-text','mobile_source_material_editor_reachable');await visible('#approved-preview-result .approved-full-text','mobile_complete_reply_preview_visible_without_footer_cover');await page.screenshot({path:'output/playwright/approved-reply-mobile.png',fullPage:true});await visible('#approved-enable','mobile_explicit_approval_button_reachable');await visible('#approved-save-draft','mobile_draft_disable_button_reachable');await page.screenshot({path:'output/playwright/approved-reply-mobile-actions.png',fullPage:true});await page.setViewportSize({width:1440,height:1040});
  await page.locator('#approved-save-draft').click();await ready();check(policyFor(source.id,groups[0].id).version===1&&ruleFor(source.id,groups[0].id).mode==='reply'&&ruleFor(source.id,groups[0].id).enabled&&ruleFor(source.id,groups[0].id).text==='原固定回复保留','draft_save_persists_cards_without_changing_existing_enabled_fixed_reply');
  await page.locator('#approved-question-add').click();await page.locator('#approved-questions textarea').nth(1).fill(' '+question+' ');await page.locator('#approved-enable').click();await ready();check((await page.locator('#approved-message').innerText()).includes('重复')&&policyFor(source.id,groups[0].id).version===1,'normalized_duplicate_complete_questions_are_rejected_without_enabling');await page.locator('.approved-question').nth(1).getByRole('button',{name:'删除此问法'}).click();
  await page.locator('#approved-enable').click();await ready();check(ruleFor(source.id,groups[0].id).mode==='approved'&&ruleFor(source.id,groups[0].id).enabled&&requests.filter(row=>row.path==='/api/reply/policy'&&row.body).at(-1).body.enabled,'explicit_approve_action_switches_only_current_group_mode');
  const frozen=clone(policyFor(source.id,groups[0].id).cards[0]);records.push({id:'approved-audit-1',source:'reply',targetId:groups[0].id,targetName:groups[0].name,decision:'reply',label:'服务器已接受，收件端未确认',text:answer,textUnavailable:false,createdAt:1791075610,timeBasis:'触发时间',pending:true,attention:false,issue:'完整问法匹配',reasonCode:'matched',approvedPolicy:{version:2,card:frozen},trigger:{senderName:'合成客户',timestamp:1791075600,text:question,textTruncated:false}},{id:'approved-audit-2',source:'reply',targetId:groups[0].id,targetName:groups[0].name,decision:'handoff',label:'本机待办',text:'',textUnavailable:false,createdAt:1791075710,timeBasis:'触发时间',pending:false,attention:true,issue:'未知问法进入人工待办',reasonCode:'unmatched',approvedPolicy:{version:2,card:null},trigger:null});
  records.push({...clone(records[0]),id:'approved-audit-3',decision:'reply',label:'提交结果未知，待人工核对',issue:'发送结果未知，请先核对微信记录，勿盲目重发。',reasonCode:'submission_unknown'});
  const late={started:deferred(),done:deferred()};previewGate=late;await page.locator('#approved-preview-input').fill(question);await page.evaluate(()=>{window.__oldApprovedPreview=previewApprovedReply();});await late.started.promise;await page.locator('#approved-reply-text').fill('新的未保存回复');late.done.resolve();await page.evaluate(()=>window.__oldApprovedPreview);check(await page.locator('#approved-preview-result').innerText()===''&&await page.locator('#approved-reply-text').inputValue()==='新的未保存回复','late_preview_cannot_replace_new_editor_draft');
  forceConflict=true;await page.locator('#approved-enable').click();await ready();const reads=requests.filter(row=>row.path==='/api/reply/policy'&&!row.body).length;await refresh();check(await page.locator('#approved-reply-text').inputValue()==='新的未保存回复'&&await page.locator('#approved-enable').isDisabled()&&(await page.locator('#approved-message').innerText()).includes('409')&&requests.filter(row=>row.path==='/api/reply/policy'&&!row.body).length===reads,'cas_conflict_preserves_draft_and_requires_explicit_reload');
  policyFor(source.id,groups[0].id).sendingPaused=true;policyFor(source.id,groups[0].id).issue='发送连接已暂停';await page.locator('#approved-reload').click();await ready();check((await page.locator('#approved-policy-state').innerText()).includes('读取处理继续')&&await page.locator('#approved-card-name').inputValue()==='并发保存的卡片','explicit_reload_displays_paused_sending_with_continued_intake');
  await page.locator('#approved-save-draft').click();await ready();check(!ruleFor(source.id,groups[0].id).enabled&&ruleFor(source.id,groups[0].id).mode==='approved','draft_action_closes_current_approved_mode');await close();await refresh();
  await page.locator('[data-view="executions"]').click();await page.waitForFunction(()=>!executionLoading&&executionRows.length===3);await page.locator('.execution-approved').first().locator('summary').click();
  const evidence=await page.locator('.execution-approved').first().innerText();check(evidence.includes(frozen.id)&&evidence.includes('策略版本 2')&&evidence.includes(material)&&evidence.includes(answer)&&evidence.includes('2026-v1'),'history_displays_frozen_card_source_and_answer_after_policy_changes');check((await page.locator('#execution-list').innerText()).includes('unmatched')&&(await page.locator('#execution-list').innerText()).includes('未知问法进入人工待办'),'history_displays_decision_reason_for_unmatched_handoff');
  const unknown=await page.locator('.execution-row').filter({hasText:'submission_unknown'}).innerText();check(unknown.includes('发送结果未知，请先核对微信记录，勿盲目重发。')&&!unknown.includes('本条未发送回复'),'unknown_submission_with_human_followup_never_claims_no_reply_was_sent');
  await page.setViewportSize({width:390,height:844});await visible(page.locator('.execution-approved').first().locator('.approved-full-text').first(),'mobile_full_audit_source_visible');await page.screenshot({path:'output/playwright/approved-reply-audit-mobile.png',fullPage:true});await visible(page.locator('.execution-approved').first().locator('.approved-full-text').last(),'mobile_full_audit_answer_visible');await page.setViewportSize({width:1440,height:1040});
  await page.locator('[data-view="workspace"]').click();await open();const held={started:deferred(),done:deferred()};writeGate=held;await page.evaluate(()=>{window.__oldPolicySave=saveApprovedReply(true);});await held.started.promise;check(await page.locator('#approved-source-text').isDisabled()&&await page.locator('#save-reply').isDisabled(),'policy_write_blocks_competing_legacy_save_and_card_edit');state.account='approved-account-b';state.runtime.source={...source,id:state.account};await refresh();await open();const newer={started:deferred(),done:deferred()};writeGate=newer;await page.evaluate(()=>{window.__newPolicySave=saveApprovedReply(true);});await newer.started.promise;held.done.resolve();await page.evaluate(()=>window.__oldPolicySave);check(await page.locator('#approved-enable').isDisabled()&&await page.evaluate(()=>replyBusy)&&await page.evaluate(()=>approvedReplyPolicy.account)==='approved-account-b','late_account_success_cannot_replace_or_unlock_new_policy_write');newer.done.resolve();await page.evaluate(()=>window.__newPolicySave);await ready();
  const failure={started:deferred(),done:deferred(),fail:true};writeGate=failure;await page.evaluate(()=>{window.__oldPolicyFailure=saveApprovedReply(false);});await failure.started.promise;state.account='approved-account-c';state.runtime.source={...source,id:state.account};await refresh();await open();failure.done.resolve();await page.evaluate(()=>window.__oldPolicyFailure);check(!(await page.locator('#approved-message').innerText()).includes('旧账号策略失败'),'late_account_failure_does_not_pollute_current_policy');
  await close();await page.evaluate(id=>selectGroup(id),groups[1].id);await open();check((await page.locator('#approved-policy-state').innerText()).includes(groups[1].id),'mixed_group_with_same_display_name_has_independent_policy');
  state.runtime.capabilities.approvedReplies=false;await refresh();check(!await page.locator('#approved-reply-dialog').isVisible()&&await page.locator('#reply-approved-option').isHidden(),'old_service_hides_approved_mode_and_closes_editor');state.runtime={mode:'demo',capabilities:{canSend:true,approvedReplies:true}};state.connection={status:'logged_in'};await refresh();check(await page.locator('#reply-approved-option').isHidden(),'demo_hides_approved_mode');
  check(!requests.some(row=>row.method==='POST'&&!['/api/select','/api/reply/policy','/api/reply/policy/preview'].includes(row.path)),'no_hook_message_legacy_reply_schedule_or_handoff_mutation');check(errors.length===0,'no_browser_javascript_errors');return {checks,realBrowser:true,allApis:'synthetic',realWindowsReadOrSend:false};
 }finally{for(const gate of gates)gate.resolve();page.off('pageerror',onError);await page.unroute('**/api/**',handler);}
}
