// Synthetic DOM and deferred APIs. No server, WeChat or native sending.
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
function node(tag='div',cls='',text=''){return {tag,className:cls,textContent:text,value:'',children:[],checked:false,hidden:false,disabled:false,open:false,events:{},
 append(...items){this.children.push(...items);},replaceChildren(...items){this.children=items;this.value='';},querySelectorAll(selector){return this.children.flatMap(child=>[...(child.tag===selector?[child]:[]),...child.querySelectorAll(selector)]);},
 addEventListener(event,fn){(this.events[event]??=[]).push(fn);},showModal(){this.open=true;},close(){if(this.open){this.open=false;for(const fn of this.events.close||[])fn();}},get selectedOptions(){return this.children.filter(item=>item.value===this.value);}};}
const nodes=new Map(),$=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);};
for(let n=1;n<=7;n++)$('schedule-batch-weekdays').append(Object.assign(node('input'),{value:String(n)}));
$('schedule-filter').value='all';
const groups=[{id:'same@chatroom',name:'同名群'},{id:'same@im.chatroom',name:'同名群'},{id:'direct',name:'联系人'},{id:'unwatched',name:'未读取'}];
const requests=[],pending=[],checks=[];let sequence=0,targetOpened=null;
const context=vm.createContext({$,el:node,Date,Set,Map,URLSearchParams,crypto:{randomUUID:()=> 'batch-id-'+(++sequence)},serviceAvailable:true,scheduleBusy:false,scheduleRenderKey:'',
 state:{account:'a',runtime:{mode:'database',source:{id:'source-a'},capabilities:{scheduledSend:true,scheduleWindows:true,scheduleBatches:true}},groups,watchedGroups:groups.slice(0,3).map(row=>row.id),jobs:[]},
 isDatabase:()=>context.state.runtime.mode==='database',supportsSchedules:()=>true,supportsScheduleWindows:()=>true,stamp:()=> '北京时间',dateKey:()=> '',groupName:id=>id,emptyCard:()=>node(),toast:()=>{},poll:async()=>{},
 api:(url,body)=>{requests.push({url,body});return new Promise((resolve,reject)=>pending.push({resolve,reject}));},
 controls:()=>run('updateScheduleBatchScope();renderSchedulePauseControls();scheduleBatchControls()'),renderSchedules:()=>run('renderWindowsSchedules()'),
 openScheduleTemplates:async(mode,target)=>{targetOpened={mode,target};$('schedule-template-dialog').showModal();}});
const run=source=>vm.runInContext(source,context),app=fs.readFileSync(path.join(__dirname,'../static/app.js'),'utf8');
run(app.slice(app.indexOf('const scheduleActionsBusy='),app.indexOf('let environmentData=')));
run(fs.readFileSync(path.join(__dirname,'../static/schedule_batch_ui.js'),'utf8'));
const template={id:'template-id-0000001',version:1,name:'索价模板',variables:['客户'],targetCount:3};
const preview=(overrides={})=>({templateId:template.id,templateVersion:template.version,templateName:template.name,mode:'weekly',clock:'23:59',at:'',weekdays:[1,3,5],windowMinutes:5,nextRun:1791043140,deadline:1791043440,
 records:groups.slice(0,3).map((row,i)=>({groupId:row.id,targetName:row.name,text:i===1?'覆盖正文':'客户您好',contentSource:i===1?'override':'template',error:'',missing:[],existingCount:0,duplicate:false})),
 readyCount:3,invalidCount:0,existingCount:0,capacity:500,canCreate:true,previewDigest:'digest-1',issues:[],...overrides});
const text=n=>n.textContent+n.children.map(text).join(' ');
function check(name,fn){fn();checks.push(name);}
async function open(){const opening=run('openScheduleBatch()');if(pending.length){pending.shift().resolve({templates:[template]});}await opening;}
function selectAll(){ $('schedule-batch-template').value=template.id;$('schedule-batch-search').value='';$('schedule-batch-select-visible').onclick();$('schedule-batch-mode').value='weekly';$('schedule-batch-mode').onchange();$('schedule-batch-clock').value='23:59';$('schedule-batch-window').value='5';for(const day of $('schedule-batch-weekdays').children)day.checked=[1,3,5].includes(Number(day.value));}
async function showPreview(result=preview()){const p=run('previewScheduleBatch()');pending.shift().resolve(result);await p;}
const job=(id,enabled=true)=>({id,group_id:groups[0].id,targetName:'同名群',text:'正文',mode:'daily',clock:'09:00',state:enabled?'active':'paused',enabled,windowMinutes:2,weekdays:[1,2,3,4,5,6,7],runs:[]});
(async()=>{
 run('renderSchedulePauseControls()');await open();selectAll();
 check('known_watched_targets_include_mixed_and_direct_without_unwatched',()=>assert.deepEqual([...run('scheduleBatchGroups')],groups.slice(0,3).map(row=>row.id)));
 $('schedule-batch-search').value='direct';$('schedule-batch-search').oninput();check('search_does_not_remove_hidden_selections',()=>{assert.equal($('schedule-batch-groups').children.length,1);assert.equal(run('scheduleBatchGroups.size'),3);assert.match($('schedule-batch-count').textContent,/已选择 3/);});
 await showPreview();check('weekly_preview_uses_shared_calendar_and_no_text_payload',()=>{const body=requests.at(-1).body;assert.deepEqual([...body.weekdays],[1,3,5]);assert.equal(body.windowMinutes,5);assert.equal(body.mode,'weekly');assert.equal(Object.hasOwn(body,'text'),false);});
 check('full_content_source_identity_and_record_capacity_visible',()=>{const output=text($('schedule-batch-results'));assert.match(output,/same@im.chatroom/);assert.match(output,/覆盖正文/);assert.match(output,/本会话完整正文覆盖/);assert.match($('schedule-batch-summary').textContent,/500/);assert.equal($('schedule-batch-create').disabled,false);});
 const unrelated={id:'new-unwatched',name:'新收到的无关会话'};context.state.groups=[...groups,unrelated];run('updateScheduleBatchScope()');
 check('unrelated_new_conversation_preserves_open_batch_and_preview',()=>{assert.equal($('schedule-batch-dialog').open,true);assert.equal(run('scheduleBatchGroups.size'),3);assert.equal($('schedule-batch-create').disabled,false);assert.match(text($('schedule-batch-results')),/覆盖正文/);});
 context.state.groups=context.state.groups.map(row=>row.id==='direct'?{...row,name:'改名联系人'}:row);run('updateScheduleBatchScope()');
 check('selected_target_rename_invalidates_preview_and_preserves_selection',()=>{assert.equal($('schedule-batch-dialog').open,true);assert.equal(run('scheduleBatchGroups.size'),3);assert.equal(run('scheduleBatchPreview'),null);assert.equal($('schedule-batch-create').disabled,true);});
 await showPreview();
 const firstId=run('scheduleBatchRequestId');$('schedule-batch-window').value='10';$('schedule-batch-window').oninput();check('editing_shared_input_invalidates_preview_without_changing_request_id',()=>{assert.equal(run('scheduleBatchPreview'),null);assert.equal(run('scheduleBatchRequestId'),firstId);assert.equal($('schedule-batch-create').disabled,true);});
 const broken=preview();broken.records[0].error='请填写变量';broken.records[0].missing=['客户'];broken.records[0].text='';broken.readyCount=2;broken.invalidCount=1;broken.canCreate=false;broken.previewDigest='';await showPreview(broken);
 check('missing_variables_block_entire_batch_and_are_located_by_id',()=>{assert.match(text($('schedule-batch-results')),/缺少：客户/);assert.equal($('schedule-batch-create').disabled,true);});
 await run('editScheduleBatchTemplate("same@chatroom")');check('fix_target_reuses_existing_template_profile_manager',()=>{assert.deepEqual(JSON.parse(JSON.stringify(targetOpened)),{mode:'manage',target:{id:template.id,groupId:'same@chatroom'}});assert.equal(run('scheduleBatchPreview'),null);assert.equal(run('scheduleBatchGroups.size'),3);});
 $('schedule-template-dialog').close();template.version=2;pending.shift().resolve({templates:[template]});await new Promise(resolve=>setImmediate(resolve));
 check('return_from_profile_manager_refreshes_version_but_requires_new_preview',()=>{assert.equal(run('scheduleBatchTemplates[0].version'),2);assert.equal(run('scheduleBatchPreview'),null);assert.equal(run('scheduleBatchGroups.size'),3);});
 await showPreview(preview({existingCount:499,canCreate:false,previewDigest:'',issues:['本批将超过500条任务记录上限']}));check('capacity_failure_blocks_all_and_reports_total_records',()=>{assert.equal($('schedule-batch-create').disabled,true);assert.match(text($('schedule-batch-results')),/500/);assert.match($('schedule-batch-summary').textContent,/499/);});
 const duplicate=preview();duplicate.records[0].existingCount=2;duplicate.records[0].duplicate=true;duplicate.records[0].error='已有启用或暂停的相同计划';duplicate.canCreate=false;await showPreview(duplicate);check('duplicate_notice_counts_records_not_enabled_jobs',()=>{assert.match(text($('schedule-batch-results')),/2 条任务记录/);assert.doesNotMatch(text($('schedule-batch-results')),/2 个启用计划/);});
 const before=requests.length;context.state.groups=Array.from({length:301},(_,i)=>({id:'bulk-'+i,name:'合成'+i}));context.state.watchedGroups=context.state.groups.map(row=>row.id);run('updateScheduleBatchScope()');await open();selectAll();await run('previewScheduleBatch()');check('more_than_300_targets_rejected_before_preview',()=>{assert.equal(requests.length,before);assert.match($('schedule-batch-message').textContent,/300/);});
 run('scheduleBatchGroups.delete("bulk-300")');await showPreview(preview({records:context.state.groups.slice(0,300).map(row=>({groupId:row.id,targetName:row.name,text:'完整正文',contentSource:'template',error:'',missing:[],existingCount:0,duplicate:false})),readyCount:300}));check('300_target_preview_is_supported',()=>assert.equal(requests.at(-1).body.groupIds.length,300));
 context.state.groups=groups;context.state.watchedGroups=groups.slice(0,3).map(row=>row.id);run('updateScheduleBatchScope()');await open();selectAll();
 const late=run('previewScheduleBatch()'),lateReply=pending.shift();$('schedule-batch-clock').value='10:00';$('schedule-batch-clock').oninput();lateReply.resolve(preview());await late;check('late_preview_cannot_replace_changed_draft',()=>assert.equal(run('scheduleBatchPreview'),null));
 $('schedule-batch-mode').value='daily';$('schedule-batch-mode').onchange();await showPreview(preview({mode:'daily',weekdays:[]}));check('daily_request_omits_weekdays',()=>assert.equal(Object.hasOwn(requests.at(-1).body,'weekdays'),false));
 $('schedule-batch-mode').value='once';$('schedule-batch-mode').onchange();await showPreview(preview({mode:'once',weekdays:[],clock:'',at:'2026-10-05T09:00'}));check('once_request_uses_at_and_omits_weekdays',()=>{assert.equal(requests.at(-1).body.clock,'');assert.equal(Object.hasOwn(requests.at(-1).body,'weekdays'),false);});
 context.state.jobs=[job('existing')];let saving=run('createScheduleBatch()'),reply=pending.shift(),body=JSON.stringify(requests.at(-1).body);
 const callCount=requests.length;await run('createScheduleBatch();pauseSchedules()');check('create_is_single_flight_and_blocks_existing_pause_and_actions',()=>{assert.equal(requests.length,callCount);assert.equal($('schedule-pause-all').disabled,true);assert.equal($('schedule-list').children[0].children[3].children[0].disabled,true);assert.equal($('schedule-batch-template').disabled,true);});
 reply.reject(Error('uncertain network'));await saving;check('uncertain_create_keeps_exact_request_and_locks_editing_without_auto_retry',()=>{assert.equal(requests.length,callCount);assert.equal($('schedule-batch-template').disabled,true);assert.equal($('schedule-batch-create').disabled,false);assert.match($('schedule-batch-message').textContent,/不会自动重试/);});
 $('schedule-batch-dialog').close();await open();saving=run('createScheduleBatch()');reply=pending.shift();check('explicit_retry_after_reopen_reuses_full_frozen_payload',()=>assert.equal(JSON.stringify(requests.at(-1).body),body));reply.resolve({batchId:'batch-receipt',createdCount:3,jobs:[job('created',false)],reused:true});await saving;
 check('replayed_success_merges_original_jobs_without_resuming_them',()=>{assert.deepEqual([...context.state.jobs].map(row=>row.id),['existing','created']);assert.equal(context.state.jobs[1].enabled,false);assert.equal($('schedule-batch-create').disabled,true);assert.match($('schedule-batch-message').textContent,/已核对原批次/);});
 const reset=$('schedule-batch-new').onclick();pending.shift().resolve({templates:[template]});await reset;selectAll();await showPreview();const retained=run('scheduleBatchRequestId');saving=run('createScheduleBatch()');pending.shift().reject(Object.assign(Error('预览已过期'),{status:409}));await saving;
 check('stale_preview_conflict_keeps_id_and_requires_new_preview',()=>{assert.equal(run('scheduleBatchPreview'),null);assert.equal(run('scheduleBatchRequestId'),retained);assert.equal($('schedule-batch-template').disabled,false);});
 await showPreview();saving=run('createScheduleBatch()');const old=pending.shift();context.state.account='b';context.state.runtime.source.id='source-b';run('updateScheduleBatchScope();renderSchedulePauseControls()');await open();selectAll();await showPreview();const newer=run('createScheduleBatch()'),newReply=pending.shift();old.resolve({batchId:'old',createdCount:99,jobs:[job('old-account')],reused:false});await saving;
 check('old_account_success_does_not_replace_or_unlock_new_request',()=>{assert.equal(context.scheduleBusy,true);assert.equal($('schedule-batch-create').disabled,true);assert.ok(context.state.jobs.every(row=>row.id!=='old-account'));assert.doesNotMatch($('schedule-batch-message').textContent,/99/);});newReply.resolve({batchId:'b',createdCount:3,jobs:[job('account-b')],reused:false});await newer;
 context.state.account='c';context.state.runtime.source.id='source-c';run('updateScheduleBatchScope();renderSchedulePauseControls()');await open();selectAll();await showPreview();saving=run('createScheduleBatch()');const rejected=pending.shift();context.state.account='d';context.state.runtime.source.id='source-d';run('updateScheduleBatchScope();renderSchedulePauseControls()');await open();rejected.reject(Object.assign(Error('旧账号失败'),{status:409}));await saving;check('old_account_failure_does_not_pollute_new_account',()=>assert.doesNotMatch($('schedule-batch-message').textContent,/旧账号失败/));
 selectAll();const read=run('previewScheduleBatch()'),readReply=pending.shift();context.state.watchedGroups=['direct'];run('updateScheduleBatchScope()');readReply.resolve(preview());await read;check('selected_reading_scope_change_discards_late_preview_and_keeps_eligible_targets',()=>{assert.equal(run('scheduleBatchGroups.size'),1);assert.equal(run('scheduleBatchPreview'),null);assert.equal($('schedule-batch-create').disabled,true);});
 context.state.runtime.capabilities.scheduleBatches=false;run('updateScheduleBatchScope()');check('old_service_hides_batch_entry',()=>assert.equal($('schedule-batch-open').hidden,true));context.state.runtime.capabilities.scheduleBatches=true;context.state.runtime.mode='demo';run('updateScheduleBatchScope()');check('demo_hides_batch_entry',()=>assert.equal($('schedule-batch-open').hidden,true));
 check('only_template_reads_batch_previews_and_batch_creation_are_called',()=>assert.ok(requests.every(row=>!row.body||['/api/jobs/batch/preview','/api/jobs/batch'].includes(row.url))));
 console.log('PASS: '+checks.length+' schedule batch controls checks (synthetic only)');
})().catch(error=>{console.error(error);process.exitCode=1;});
